version: "3"

services:
  lec_letter_initial_service:
    build:
      context: ./
      args:
        ENV_STRING: |
          DB_PORT=
          DB_HOST=
          DB_USER=
          DB_PASSWORD=
          DB_NAME=
    container_name: manual_manager_backend
    restart: unless-stopped
    ports:
      - "6501:80"

  manual_module_db:
    image: postgres:11.5-alpine
    container_name: manual_module_db
    ports:
      - "16302:5432"
    volumes:
      - manual_module_postgres_db:/var/lib/posgresql/data/

volumes:
  manual_module_postgres_db:


networks:
  default:
    external:
      name: CtCloud-network