version: "3"

services:
  lec_letter_initial_service:
    build:
      context: ./
      args:
        ENV_STRING: |
          DB_PORT=5432
          DB_HOST=lec_letter_initial_db
          DB_USER=postgres
          DB_PASSWORD=postgres
          DB_NAME=postgres
          GENERATOR_HOST=document_generator_grpc:80
    container_name: lec_letter_initial_service
    restart: unless-stopped
    ports:
      - "6501:80"

  lec_letter_initial_db:
    image: postgres:11.5-alpine
    container_name: lec_letter_initial_db
    ports:
      - "16302:5432"
    volumes:
      - lec_letter_initial_postgres_db:/var/lib/posgresql/data/

volumes:
  lec_letter_initial_postgres_db:


networks:
  default:
    external:
      name: CtCloud-network